/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../core/context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/auth`; params?: Router.UnknownInputParams; } | { pathname: `/customer/cart`; params?: Router.UnknownInputParams; } | { pathname: `/customer/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/customer/home`; params?: Router.UnknownInputParams; } | { pathname: `/customer`; params?: Router.UnknownInputParams; } | { pathname: `/customer/ordercomplete`; params?: Router.UnknownInputParams; } | { pathname: `/customer/orders`; params?: Router.UnknownInputParams; } | { pathname: `/customer/products`; params?: Router.UnknownInputParams; } | { pathname: `/customer/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../core/context/CartContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/checkout`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/home`; params?: Router.UnknownOutputParams; } | { pathname: `/customer`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/ordercomplete`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/products`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../core/context/CartContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/auth${`?${string}` | `#${string}` | ''}` | `/customer/cart${`?${string}` | `#${string}` | ''}` | `/customer/checkout${`?${string}` | `#${string}` | ''}` | `/customer/home${`?${string}` | `#${string}` | ''}` | `/customer${`?${string}` | `#${string}` | ''}` | `/customer/ordercomplete${`?${string}` | `#${string}` | ''}` | `/customer/orders${`?${string}` | `#${string}` | ''}` | `/customer/products${`?${string}` | `#${string}` | ''}` | `/customer/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../core/context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/auth`; params?: Router.UnknownInputParams; } | { pathname: `/customer/cart`; params?: Router.UnknownInputParams; } | { pathname: `/customer/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/customer/home`; params?: Router.UnknownInputParams; } | { pathname: `/customer`; params?: Router.UnknownInputParams; } | { pathname: `/customer/ordercomplete`; params?: Router.UnknownInputParams; } | { pathname: `/customer/orders`; params?: Router.UnknownInputParams; } | { pathname: `/customer/products`; params?: Router.UnknownInputParams; } | { pathname: `/customer/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
